title: Look at my blog, my blog is amazing
motto: "\"Put your best practices away!!\" -- why the lucky stiff"
email: mailto:feedward@gmail.com
twitter: https://twitter.com/feedward
github: https://github.com/feedward
